version: '3.8'

services:
  fta-fmea:
    image: fta-fmea-ui:v0.1
    environment:
      API_URL: ${API_URL:-http://localhost:9999/}
      ADMIN_REGISTRATION_ONLY: ${ADMIN_REGISTRATION_ONLY:-false}
    ports:
      - "8080:80"
    depends_on:
      - fta-fmea-server


  fta-fmea-server:
    image: fta-fmea:v0.1
    ports:
      - "9999:9999"
    depends_on:
      - db-server
    environment:
      REPOSITORY_URL: ${REPOSITORY_URL:-http://db-server:7200/repositories/fta-fmea}


  db-server:
    build:
      context: ../shared/db-server
    expose:
      - "7200"
    ports:
      - "7200:7200"
    restart: always
    volumes:
      - ./db-server:/opt/graphdb/home

volumes:
  db-server:
